-- Seed editorial descriptions for select cities
update public.cities set description = 'London offers one of the world''s richest gay urban lives: layered, metropolitan, and never confined to a single mood. Soho still provides the symbolic centre, but the city''s real appeal lies in its breadth, from historic pubs and louche cabaret rooms to handsome cocktail bars and all-night institutions. It is a scene of contrasts: theatrical yet self-possessed, traditional yet constantly remade.' where slug = 'london';

update public.cities set description = 'Madrid is a city that wears its gay life lightly but confidently. Chueca remains its social anchor, though the broader impression is one of ease: terraces full in the early evening, bars that gather momentum slowly, and nights that unfold with little urgency and great style. There is glamour here, certainly, but also warmth, openness, and a sense that pleasure belongs in everyday life.' where slug = 'madrid';

update public.cities set description = 'Sitges has the rare gift of feeling both polished and entirely unforced. Its gay scene is woven neatly into the fabric of the town: beach, promenade, bars, and late-night spots all within easy reach of one another. By day it is bright, sociable, and faintly languid; by night, more flirtatious. Few places combine seaside charm and gay visibility with such apparent ease.' where slug = 'sitges';

update public.cities set description = 'Amsterdam''s gay life feels less staged than simply absorbed into the life of the city itself. There is no need for grand declarations when freedom is so embedded in the atmosphere: canal-side cafés, dark bars, club nights, and cultural spaces all exist with a kind of quiet assurance. The mood is liberal, urbane, and slightly hedonistic, though rarely in a way that feels forced.' where slug = 'amsterdam';

update public.cities set description = 'Copenhagen''s gay scene is modest in scale but strong in character. A small collection of long-running venues gives it a sense of permanence, while the city''s broader mood, civil, stylish, and quietly permissive, shapes the experience around them. It is not a place of spectacle so much as one of atmosphere: intimate bars, warm service, late nights, and a scene that reveals itself gently.' where slug = 'copenhagen';

update public.cities set description = 'Manchester remains one of Britain''s defining gay cities, with Canal Street still lending the scene a rare clarity and centre of gravity. What distinguishes it is not polish alone but personality: exuberant, resilient, proudly local. The city''s gay life moves easily between cheerful chaos and genuine community, with classic bars, club nights, and drag-soaked evenings carrying a spirit that feels distinctly Mancunian.' where slug = 'manchester';

update public.cities set description = 'Torremolinos has long understood the pleasures of a gay resort town and still delivers them with confidence. Its scene is open-air and sunlit, centred on beach clubs, plazas, terraces, and the easy drift from afternoon to evening to late night. International in crowd but relaxed in temperament, it offers a kind of holiday freedom that feels less performative than deeply ingrained.' where slug = 'torremolinos';
